  DATA PREPROCESSING AND FEATURE ENGINEERING IN MACHINE LEARNING
  
Data Loading & Basic Exploration:

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
adult= pd.read_csv('/content/adult_with_headers (1).csv')

In [3]:
adult

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K
2,38,Private,215646,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
3,53,Private,234721,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K
4,28,Private,338409,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26870,38,Private,179488,Assoc-acdm,12.0,Divorced,Craft-repair,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
26871,53,Private,48343,HS-grad,9.0,Married-civ-spouse,Transport-moving,Husband,White,Male,0.0,1902.0,40.0,United-States,>50K
26872,28,Local-gov,100270,Bachelors,13.0,Divorced,Prof-specialty,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
26873,42,Private,227065,Some-college,10.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,15024.0,0.0,32.0,United-States,>50K
26874,40,Private,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
adult.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K
2,38,Private,215646,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
3,53,Private,234721,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K
4,28,Private,338409,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K

In [5]:
adult.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,26875.000000,2.687500e+04,26874.000000,26874.000000,26874.000000,26874.000000
mean,38.614512,1.897247e+05,10.084692,1091.752995,86.985376,40.408648
std,13.672291,1.051341e+05,2.564925,7501.346726,402.254353,12.302287
min,17.000000,1.200000e+01,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.179630e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.784210e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.368785e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [6]:
adult.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26875 entries, 0 to 26874
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             26875 non-null  int64
 1   workclass       26875 non-null  object
 2   fnlwgt          26875 non-null  int64
 3   education       26874 non-null  object
 4   education_num   26874 non-null  float64
 5   marital_status  26874 non-null  object
 6   occupation      26874 non-null  object
 7   relationship    26874 non-null  object
 8   race            26874 non-null  object
 9   sex             26874 non-null  object
 10  capital_gain    26874 non-null  float64
 11  capital_loss    26874 non-null  float64
 12  hours_per_week  26874 non-null  float64
 13  native_country  26874 non-null  object
 14  income          26874 non-null  object
dtypes: float64(4), int64(2), object(9)
memory usage: 3.1+ MB

In [7]:
adult.isnull()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26870,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26871,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26872,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26873,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26874,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True

In [8]:
adult.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         1
education_num     1
marital_status    1
occupation        1
relationship      1
race              1
sex               1
capital_gain      1
capital_loss      1
hours_per_week    1
native_country    1
income            1
dtype: int64

In [9]:
from sklearn.impute import SimpleImputer
num_cols=adult.select_dtypes(include=["int64","float64"]).columns
cat_cols=adult.select_dtypes(include=["object"]).columns

In [10]:
num_imputer=SimpleImputer(strategy="median")
cat_imputer=SimpleImputer(strategy="most_frequent")
adult[num_cols]=num_imputer.fit_transform(adult[num_cols])
adult[cat_cols]=cat_imputer.fit_transform(adult[cat_cols])

Feature Scaling :

Standard Scaling :

In [11]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
adult_standard_scaled = adult.copy()
adult_standard_scaled[num_cols] = std_scaler.fit_transform(adult[num_cols])

Min-Max Scaling :

In [12]:
from sklearn.preprocessing import MinMaxScaler

mm_scaler = MinMaxScaler()
adult_minmax_scaled = adult.copy()
adult_minmax_scaled[num_cols] = mm_scaler.fit_transform(adult[num_cols])

In [ ]:
# Standard Scaling :
#Preferred When	: During Linear Regression, Logistic Regression, SVM, PCA
#Reason : Centers data (mean=0, std=1), assumes Gaussian distribution


#Min-Max Scaling :
#Preferred When	: Neural Networks, KNN, Distance-based models
#Reason : Keeps values in fixed range [0,1], preserves distribution

Encoding Techniques :

One-Hot Encoding :

In [13]:
adult_encoding = pd.get_dummies(adult, columns=["workclass","education","marital_status","occupation","relationship","race","sex","native_country"], drop_first=True)
adult_encoding

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,income,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,...,native_country_ Portugal,native_country_ Puerto-Rico,native_country_ Scotland,native_country_ South,native_country_ Taiwan,native_country_ Thailand,native_country_ Trinadad&Tobago,native_country_ United-States,native_country_ Vietnam,native_country_ Yugoslavia
0,39.0,77516.0,13.0,2174.0,0.0,40.0,<=50K,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,50.0,83311.0,13.0,0.0,0.0,13.0,<=50K,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,38.0,215646.0,9.0,0.0,0.0,40.0,<=50K,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,53.0,234721.0,7.0,0.0,0.0,40.0,<=50K,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,28.0,338409.0,13.0,0.0,0.0,40.0,<=50K,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26870,38.0,179488.0,12.0,0.0,0.0,40.0,<=50K,False,False,False,...,False,False,False,False,False,False,False,True,False,False
26871,53.0,48343.0,9.0,0.0,1902.0,40.0,>50K,False,False,False,...,False,False,False,False,False,False,False,True,False,False
26872,28.0,100270.0,13.0,0.0,0.0,40.0,<=50K,False,True,False,...,False,False,False,False,False,False,False,True,False,False
26873,42.0,227065.0,10.0,15024.0,0.0,32.0,>50K,False,False,False,...,False,False,False,False,False,False,False,True,False,False
26874,40.0,12.0,10.0,0.0,0.0,40.0,<=50K,False,False,False,...,False,False,False,False,False,False,False,True,False,False

Label Encoding :

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
adult["education_encoded"] = le.fit_transform(adult["education"])
adult[["education", "education_encoded"]].head()

    education  education_encoded
0   Bachelors                  9
1   Bachelors                  9
2     HS-grad                 11
3        11th                  1
4   Bachelors                  9

In [15]:
cat_cols

Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country', 'income'],
      dtype='object')

In [16]:
#Pros & Cons of Encoding Techniques

#One-Hot Encoding :

#Pros :

#No ordinal relationship assumed
#Works well for nominal data

#Cons :

#Increases dimensionality
#Not scalable for high-cardinality features

#Label Encoding :

#Pros :

#Memory efficient
#Fast and simple

#Cons :

#Introduces false ordinal relationship
#Can mislead distance-based models

Feature Engineering :

Feature 1: Capital Gain Indicator :

In [17]:
adult["has_capital_gain"] = (adult["capital_gain"] > 0).astype(int)

In [ ]:
#1 : individual has a capital gain
#0 : no capital gain
#Capital gains are strongly associated with higher income levels.

Rationale :

In [ ]:
#Capital gains are strongly associated with higher income levels. Creating a binary indicator helps the model:
#Capture the presence or absence of capital gains
#Reduce sensitivity to extreme capital gain values
#Improve interpretability and predictive power

Feature 2: Work Intensity :

In [18]:
adult["work_intensity"] = adult["hours_per_week"] * adult["education_num"]

In [19]:
#hours-per-week : working effort
#education-num : education level
#Income is influenced not just by working hours or education individually, but by their combined effect.

Rationale :

In [20]:
#Income is influenced not just by working hours or education individually, but by their combined effect.
#The work_intensity feature represents how education and work commitment together impact earning potential.

Transformation of Skewed Features :

In [21]:
adult["capital_gain"].skew()       # check skew
#The capital-gain feature is highly right-skewed, meaning most values are small while a few extremely large values dominate the distribution

np.float64(11.810860624748464)

Log Transformation :

In [22]:
adult["capital_gain_log"] = np.log1p(adult["capital_gain"])

In [23]:
#Observation:

#The capital-gain feature is highly right-skewed, meaning most values are small while a few extremely large values dominate the distribution.

Justification :

In [24]:
#Log transformation is applied to handle skewness effectively

#Reduces the impact of extreme outliers

#Makes the distribution more symmetric

#Improves performance of linear and distance-based models

#log1p() is used to safely handle zero values